import { beforeAll, test, vi } from "vitest";
import { parseConfig } from "@lorenz/config";
import { assert } from "@lorenz/test-utils";

import { registerBuiltinBackends } from "../src/daemon.js";

import { main, parseCliArgs, projectUrlForSettings } from "@lorenz/cli";

// projectUrlForSettings and parseConfig resolve providers through the process-default
// registries, so populate them the same way the CLI entrypoints do.
beforeAll(() => {
  registerBuiltinBackends();
});

test("CLI accepts workflow path and TS runtime flags", () => {
  assert.deepEqual(
    parseCliArgs(["--once", "--dry-run", "--no-tui", "--port", "4100", "WORKFLOW_FULL_ACCESS.md"]),
    {
      status: "ok",
      options: {
        workflowPath: "WORKFLOW_FULL_ACCESS.md",
        once: true,
        dryRun: true,
        tui: false,
        dashboard: true,
        port: 4100,
        logsRoot: null,
        claimStore: { backend: null, path: null, ownerStaleMs: null },
      },
    },
  );
});

test("CLI defaults to a TUI daemon when only workflow path is supplied", () => {
  assert.deepEqual(parseCliArgs(["WORKFLOW.md"]), {
    status: "ok",
    options: {
      workflowPath: "WORKFLOW.md",
      once: false,
      dryRun: false,
      tui: true,
      dashboard: true,
      port: null,
      logsRoot: null,
      claimStore: { backend: null, path: null, ownerStaleMs: null },
    },
  });
  assert.deepEqual(parseCliArgs(["--logs-root", "tmp/custom-logs", "--port", "0", "WORKFLOW.md"]), {
    status: "ok",
    options: {
      workflowPath: "WORKFLOW.md",
      once: false,
      dryRun: false,
      tui: true,
      dashboard: true,
      port: 0,
      logsRoot: "tmp/custom-logs",
      claimStore: { backend: null, path: null, ownerStaleMs: null },
    },
  });
  assert.deepEqual(parseCliArgs(["--logs-root=tmp/custom-logs", "--port=0", "WORKFLOW.md"]), {
    status: "ok",
    options: {
      workflowPath: "WORKFLOW.md",
      once: false,
      dryRun: false,
      tui: true,
      dashboard: true,
      port: 0,
      logsRoot: "tmp/custom-logs",
      claimStore: { backend: null, path: null, ownerStaleMs: null },
    },
  });
});

test("CLI accepts explicit durable claim store options", () => {
  assert.deepEqual(
    parseCliArgs([
      "--claim-store",
      "turso",
      "--claim-store-path",
      "tmp/claims.db",
      "--claim-store-owner-stale-ms",
      "90000",
      "WORKFLOW.md",
    ]),
    {
      status: "ok",
      options: {
        workflowPath: "WORKFLOW.md",
        once: false,
        dryRun: false,
        tui: true,
        dashboard: true,
        port: null,
        logsRoot: null,
        claimStore: { backend: "turso", path: "tmp/claims.db", ownerStaleMs: 90000 },
      },
    },
  );
});

test("CLI reports help and invalid arguments", () => {
  const help = parseCliArgs(["--help"]);
  assert.equal(help.status, "help");
  assert.match(help.message, /Usage: lorenz \[options\] \[workflowPath\]/);
  assert.match(help.message, /--logs-root <path>/);
  assert.deepEqual(parseCliArgs(["one.md", "two.md"]), {
    status: "error",
    message: "error: too many arguments. Expected 1 argument but got 2.",
  });
  assert.deepEqual(parseCliArgs(["--port", "-1"]), {
    status: "error",
    message: "--port must be a non-negative integer",
  });
  assert.deepEqual(parseCliArgs(["--logs-root"]), {
    status: "error",
    message: "--logs-root requires a path",
  });
  assert.deepEqual(parseCliArgs(["--claim-store", "postgres"]), {
    status: "error",
    message: "claim store backend must be one of: memory, sqlite, turso",
  });
});

test("root CLI help is generated by Commander and includes subcommands", async () => {
  const spy = vi.spyOn(process.stdout, "write").mockReturnValue(true);

  assert.equal(await main(["--help"]), 0);

  const output = spy.mock.calls.map((call) => String(call[0])).join("");
  spy.mockRestore();

  assert.match(output, /Usage: lorenz \[options\] \[command\] \[workflowPath\]/);
  assert.match(output, /doctor \[options\] \[workflowPath\]/);
  assert.match(output, /runs \[options\]/);
  assert.match(output, /status \[options\] \[workflowPath\]/);
  assert.match(output, /refresh \[options\] \[workflowPath\]/);
  assert.match(output, /stop \[options\] \[workflowPath\]/);
});

test("CLI dashboard options derive project URL from tracker project slug", () => {
  assert.equal(
    projectUrlForSettings(parseConfig({ tracker: { kind: "linear", project_slug: "mono dev" } })),
    "https://linear.app/project/mono%20dev/issues",
  );
  assert.equal(
    projectUrlForSettings(
      parseConfig({
        tracker: {
          kind: "jira",
          base_url: "https://example.atlassian.net/",
          project_keys: ["ENG"],
        },
      }),
    ),
    "https://example.atlassian.net/jira/software/c/projects/ENG/issues",
  );
  assert.equal(projectUrlForSettings(parseConfig()), undefined);
});
