[tools]
node = "24"
pnpm = "9"

[hooks]
enter = "pnpm install --frozen-lockfile || true"

[settings]
experimental = true

[tasks.build]
run = "pnpm build"

[tasks.format]
run = "pnpm format"

[tasks.lint-fix]
run = "pnpm lint:fix"

[tasks.lint]
run = "pnpm lint"

[tasks.typecheck]
run = "pnpm typecheck"

[tasks.test]
run = "pnpm test"
depends = ["build"]


[tasks.tidy]
depends = ["format", "lint-fix"]

[tasks.check]
depends = ["typecheck", "test", "lint"]
