import { test, vi } from "vitest";
import { parseConfig } from "@symphony/config";

import { assert } from "../../../test/assert.js";

import { main, parseCliArgs, projectUrlForSettings } from "@symphony/cli";

test("CLI accepts Elixir-compatible workflow path and TS runtime flags", () => {
  assert.deepEqual(
    parseCliArgs(["--once", "--dry-run", "--no-tui", "--port", "4100", "WORKFLOW_FULL_ACCESS.md"]),
    {
      status: "ok",
      options: {
        workflowPath: "WORKFLOW_FULL_ACCESS.md",
        once: true,
        dryRun: true,
        tui: false,
        dashboard: true,
        port: 4100,
        logsRoot: null,
      },
    },
  );
});

test("CLI defaults to a TUI daemon when only workflow path is supplied", () => {
  assert.deepEqual(parseCliArgs(["WORKFLOW.md"]), {
    status: "ok",
    options: {
      workflowPath: "WORKFLOW.md",
      once: false,
      dryRun: false,
      tui: true,
      dashboard: true,
      port: null,
      logsRoot: null,
    },
  });
  assert.deepEqual(parseCliArgs(["--logs-root", "tmp/custom-logs", "--port", "0", "WORKFLOW.md"]), {
    status: "ok",
    options: {
      workflowPath: "WORKFLOW.md",
      once: false,
      dryRun: false,
      tui: true,
      dashboard: true,
      port: 0,
      logsRoot: "tmp/custom-logs",
    },
  });
  assert.deepEqual(parseCliArgs(["--logs-root=tmp/custom-logs", "--port=0", "WORKFLOW.md"]), {
    status: "ok",
    options: {
      workflowPath: "WORKFLOW.md",
      once: false,
      dryRun: false,
      tui: true,
      dashboard: true,
      port: 0,
      logsRoot: "tmp/custom-logs",
    },
  });
});

test("CLI reports help and invalid arguments", () => {
  const help = parseCliArgs(["--help"]);
  assert.equal(help.status, "help");
  assert.match(help.message, /Usage: symphony-ts \[options\] \[workflowPath\]/);
  assert.match(help.message, /--logs-root <path>/);
  assert.deepEqual(parseCliArgs(["one.md", "two.md"]), {
    status: "error",
    message: "error: too many arguments. Expected 1 argument but got 2.",
  });
  assert.deepEqual(parseCliArgs(["--port", "-1"]), {
    status: "error",
    message: "--port must be a non-negative integer",
  });
  assert.deepEqual(parseCliArgs(["--logs-root"]), {
    status: "error",
    message: "--logs-root requires a path",
  });
});

test("root CLI help is generated by Commander and includes subcommands", async () => {
  const spy = vi.spyOn(process.stdout, "write").mockReturnValue(true);

  assert.equal(await main(["--help"]), 0);

  const output = spy.mock.calls.map((call) => String(call[0])).join("");
  spy.mockRestore();

  assert.match(output, /Usage: symphony-ts \[options\] \[command\] \[workflowPath\]/);
  assert.match(output, /runs \[options\]/);
});

test("CLI dashboard options derive project URL from tracker project slug", () => {
  assert.equal(
    projectUrlForSettings(parseConfig({ tracker: { project_slug: "mono dev" } })),
    "https://linear.app/project/mono%20dev/issues",
  );
  assert.equal(projectUrlForSettings(parseConfig()), undefined);
});
